version: '3'
# persistent volumes
volumes:
    prometheus_data: {}
    grafana_data: {}

services:
# Prometheus server
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    extra_hosts:
      - "hv-eu.one:IP_ADDRESS_OF_1st_NODE"
      - "hv-us.one:IP_ADDRESS_OF_2nd_NODE"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/file_sd/:/etc/prometheus/file_sd/
      - ./prometheus/rules/:/etc/prometheus/rules/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - '9090:9090'
    restart: always
# Alertmanager for Prometheus Server
  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    restart: always
# Node-exporter for localhost
  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: host
    cap_add:
      - SYS_TIME
    restart: always
# Grafana Server
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards/misc/:/var/lib/grafana/dashboards/misc/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    restart: always
